<?php
session_start();
require_once 'config/database.php';

// Enable error reporting
error_reporting(E_ALL);
ini_set('display_errors', 1);

if (isset($_GET['id']) && is_numeric($_GET['id'])) {
    $reportId = intval($_GET['id']);
    
    try {
        $db = new Database();
        $conn = $db->getConnection();
        
        // Get report details
        $stmt = $conn->prepare("SELECT * FROM Report WHERE id = ?");
        $stmt->execute([$reportId]);
        $report = $stmt->fetch(PDO::FETCH_ASSOC);
        
        if ($report) {
            // In a real application, you would generate or display the full report here
            // For now, we'll just show some basic info
            header('Content-Type: text/html; charset=utf-8');
            ?>
            <!DOCTYPE html>
            <html>
            <head>
                <title>View Report - <?php echo htmlspecialchars($report['name']); ?></title>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
                <style>
                    body {
                        font-family: Arial, sans-serif;
                        line-height: 1.6;
                        margin: 0;
                        padding: 20px;
                        background: #f8fafc;
                    }
                    .report-container {
                        max-width: 800px;
                        margin: 0 auto;
                        background: white;
                        padding: 30px;
                        border-radius: 10px;
                        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                    }
                    .report-header {
                        border-bottom: 2px solid #e2e8f0;
                        padding-bottom: 20px;
                        margin-bottom: 20px;
                    }
                    .report-title {
                        font-size: 24px;
                        color: #1e293b;
                        margin: 0 0 10px 0;
                    }
                    .report-meta {
                        color: #64748b;
                        font-size: 14px;
                    }
                    .report-content {
                        color: #334155;
                    }
                    .back-button {
                        display: inline-block;
                        padding: 10px 20px;
                        background: #2563eb;
                        color: white;
                        text-decoration: none;
                        border-radius: 5px;
                        margin-bottom: 20px;
                    }
                    .back-button:hover {
                        background: #1d4ed8;
                    }
                </style>
            </head>
            <body>
                <div class="report-container">
                    <a href="reports.php" class="back-button">
                        <i class="fas fa-arrow-left"></i> Back to Reports
                    </a>
                    
                    <div class="report-header">
                        <h1 class="report-title"><?php echo htmlspecialchars($report['name']); ?></h1>
                        <div class="report-meta">
                            <p><strong>Type:</strong> <?php echo htmlspecialchars($report['type']); ?></p>
                            <p><strong>Generated:</strong> <?php echo date('F j, Y', strtotime($report['createdAt'])); ?></p>
                            <p><strong>Status:</strong> <?php echo htmlspecialchars($report['status']); ?></p>
                        </div>
                    </div>
                    
                    <div class="report-content">
                        <h2>Description</h2>
                        <p><?php echo nl2br(htmlspecialchars($report['description'])); ?></p>
                        
                        <h2>Statistics</h2>
                        <ul>
                            <li>Downloads: <?php echo intval($report['download_count']); ?></li>
                            <li>File Size: <?php echo htmlspecialchars($report['file_size']); ?></li>
                            <li>Generated By: <?php echo htmlspecialchars($report['generated_by']); ?></li>
                        </ul>
                        
                        <?php if ($report['status'] === 'Published'): ?>
                        <p>
                            <a href="download_report.php?id=<?php echo $report['id']; ?>" class="back-button">
                                <i class="fas fa-download"></i> Download Report
                            </a>
                        </p>
                        <?php endif; ?>
                    </div>
                </div>
            </body>
            </html>
            <?php
            exit;
        }
    } catch (PDOException $e) {
        error_log("View error: " . $e->getMessage());
    }
}

// If we get here, something went wrong
header('Location: reports.php?error=view_failed');
exit;
